version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "develop"
    labels:
      - "pip dependencies"
      - "security"
    reviewers:
      - "duarte@alum.mit.edu" 